version: "3"


services:
  database:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"


  api:
    build: .
    volumes:
      - .:/pay-system
    ports:
      - "2424:2424"
    command:
      - uvicorn
      - main:app
      - --host=0.0.0.0
      - --port=2424
    depends_on:
      - database
      - redis_db

volumes:
  postgres_data:
